### PR TITLE
- Add install target for the faiss library and headers to the

### PR DESCRIPTION
**Pull request by mohnishkodnani**
CMakeLists.txt, so we can install the libs and headers with make
install.

### CODE REVIEW

**Comment by mdouze** [comment]
@hlzz, any comment?

**Comment by mohnishkodnani** [comment]
I am not putting the gpu headers because I currently dont have an environment where I can compile the gpu version of faiss and also install those. 
But that can come as another pull request i guess, if this one makes sense.

**Comment by mohnishkodnani** [comment]
@hlzz install target is what i have added.

**Comment by mohnishkodnani** [comment]
Let me know what I can do now ?

**Comment by mdouze** [comment]
Thanks @mohnishkodnani and @hlzz, then I accept the PR.

**Pull request merged**
