### PR TITLE
Using DirectMapAdd to fix IVFFLAT parallel adding

### PR DESCRIPTION
**Pull request by shengjun1985**
Signed-off-by: shengjun.li <shengjun.li@zilliz.com>

When `direct_map.type` is `DirectMap::Type::Array`, IVFFLAT parallel adding may fail here.
```C++
void DirectMap::add_single_id(idx_t id, idx_t list_no, size_t offset) {
    ...
    if (type == Array) {
        assert(id == array.size());
```

However, DirectMapAdd has solved it.

### CODE REVIEW

**Comment by KinglittleQ** [comment]
This is a bug I introduced in https://github.com/facebookresearch/faiss/pull/1805. I didn't aware that the inserted ids may not be in ascending order due to OMP parallel 😓 .

**Comment by mdouze** [comment]
OK, what was wrong here? Is it when list_no = -1 or something more complex? 
It does not matter that the inserted ids are not in ascending order.

**Comment by KinglittleQ** [comment]
@mdouze `DirectMap::add_single_id` always appends `list_no|offset` into `array` and requires `id` should be the same as the array size. `id` may exceed the array size if it come out of order.

https://github.com/facebookresearch/faiss/blob/31bd194e2e589baf29a2aef2810cf28b40610a1d/faiss/invlists/DirectMap.cpp#L85-L101

**Comment by mdouze** [comment]
Thanks! this sounds good.

**Pull request closed without merging**
