### PR TITLE
Add IVF statistics info for search_with_parameters

### PR DESCRIPTION
**Pull request by JinHai-CN**
Signed-off-by: JinHai-CN <hai.jin@zilliz.com>

No, IVF completed statistics information when we use search_with_parameters in IVFlib.cpp to search the vector.

### CODE REVIEW

**Comment by JinHai-CN** [comment]
@mdouze 
'83 - TestGpuIndexIVFPQ.Float16Coarse ' is failed.
Do we need to run the CI again?

**Comment by mdouze** [comment]
It would be better if the timing statistics were returned by the function, like `nb_dis_ptr`. The rationale is that this function is intended for use from multiple threads, where accessing the global var would cause thread conflicts.

**Comment by JinHai-CN** [comment]
1. IVF indexes already use OpenMP in the search function. Will the search function really be used in multiple threads cases?

2. From the code structure. Yes, it will be better to avoid using global shared variables.

**Comment by mdouze** [comment]
I integrated this modification to https://github.com/facebookresearch/faiss/pull/1438

**Pull request closed without merging**
