### PR TITLE
Add TravisCI config.

### PR DESCRIPTION
**Pull request by beauby**
Builds on:
+ Linux with g++ libblas/libblapack
+ Linux with g++ libatlas
+ Linux with g++ libopenblas
+ Linux with clang++ libopenblas
+ OSX with g++ libopenblas
+ OSX with clang++ libopenblas

### CODE REVIEW

**Comment by mdouze** [comment]
Thanks for the PR 

Why did you change the comments in makefile.inc.Linux? They could be useful for some people.

**Comment by beauby** [comment]
@mdouze I put back the comments about the required packages. The intention was to remove the static linkage bits.

**Comment by mdouze** [comment]
Do you plan to add the python tests before committing?

**Comment by beauby** [comment]
Rebased on top of #466.

**Comment by Enet4** [comment]
Just gave this a try on my machine. Is compiling the GPU version supposed to work at the moment? It would be nice if `./configure` would also take care of identifying the right CUDA flags.

I also noticed that some changes are required in the C API after this PR, but I can send a fix once it has been merged.

**Pull request merged**
