### PR TITLE
Classes inherited from VectorTransform for c_api

### PR DESCRIPTION
**Pull request by ava57r**
inherite from  LinearTransform doesn't work here.

### CODE REVIEW

**Comment by mdouze** [comment]
@Enet4 could you take a look?

@ava57r could you do me a favor and merge the PRs related to the C api into a single PR? The overhead to import the PRs to the FB build system is high so I'd rather not do it for just 1-2 lines of code. Thanks!

**Comment by ava57r** [comment]
> could you do me a favor and merge the PRs related to the C api into a single PR? The overhead to import the PRs to the FB build system is high so I'd rather not do it for just 1-2 lines of code. Thanks!
 OK :)

**Comment by ava57r** [comment]
https://github.com/facebookresearch/faiss/pull/1868 merged with this PR

**Review by Enet4 — APPROVED** [review]
No objections. Indeed, the fake inheritance trick works better when done against the base.

**Pull request closed without merging**
