### PR TITLE
read/write index with std::function wrapper

### PR DESCRIPTION
**Pull request by dengoswei**
1. add std::function wrapper to read/write index; 
   In our case, we may read/write index from/to hdfs. 

2. add IndexIVF::access;

### CODE REVIEW

**Comment by mdouze** [comment]
Hi 

Thanks for the PR. The modification to the I/O functions to make them generic is something we have on our todo list for a long time, so it is useful. So I will consider to accept it if: 

- the access function is removed (it is unrelated to the I/O part)

- no `std::function`. There should be a virtual class with virtual functions `write` and `read`, that can be implemented as FILE* objects or otherwise. 

Thanks

**Comment by dengoswei** [comment]
why not std::function ? Virtual class with virtual functions `write` and `read` can be wrapped with std::function, and write_index won't need any read interface.

**Comment by mdouze** [comment]
Please follow the Faiss conventions.

**Comment by dengoswei** [comment]
well. 
https://github.com/facebookresearch/faiss/compare/master...dengoswei:master

**Comment by mdouze** [comment]
Thanks for the update. It looks almost good for acceptance. 

Could you: 

- remove the PFN_ prefix from the macros and delete the old versions of the macros

- there are some functions that require a file id for memory mapping. Could you add a get_fileno() method to the IOWriter/IOReader objects and that FAISS_THROW_MSG()  by default but returns a proper file descriptor for the FileIOXXX versions

- remove unrelated changes in tests/test_pairs_decoding.cpp

Thanks a lot this will be a useful diff!

**Comment by dengoswei** [comment]
- remove the PFN_ prefix from the macros and delete the old versions of the macros
   DONE
- remove unrelated changes in tests/test_pairs_decoding.cpp
   DONE
- there are some functions that require a file id for memory mapping
  check out read_InvertedLists;

**Comment by mdouze** [comment]
Thanks, you can also rename `pfn_read` and `pfn_write` with `f`. The diff will be easier to read.

**Comment by dengoswei** [comment]
up;

**Comment by mdouze** [comment]
Thanks. We will pass the diff through our internal tests next week.

**Comment by mdouze** [comment]
Sorry for the delay. The tests pass, so I am accepting the PR.

**Pull request merged**
