### PR TITLE
Mention CUDA version required to run faiss-gpu

### PR DESCRIPTION
**Pull request by ashishmadeti**
As discussed in #371

### CODE REVIEW

**Comment by wickedfoo** [comment]
Faiss GPU only requires CUDA 7.5 or greater. The problem you seem to be having is specific to 9.1?

**Comment by Enet4** [comment]
@wickedfoo I believe the issue here is that the conda package is pre-compiled specifically for CUDA 9.0, so it will only work for this version.

**Comment by ailzhang** [comment]
Hi, actually we've added more support including CUDA8.0/CUDA9.0/CUDA9.1 and updating the INSTALL.md here. #395

**Comment by ashishmadeti** [comment]
@wickedfoo I am using CUDA 9.0 with the conda package

@ailzhang #395 makes more sense. But by default, conda installs the CUDA 9.0 version.

**Comment by mdouze** [comment]
addressed by #392

**Comment by ailzhang** [comment]
@ashishmadeti  I tried on several computer which has CUDA9.0 installed, if I don't have cuda90 feature in my conda list, the default package is cuda8.0 one.

**Pull request closed without merging**
