### PR TITLE
Fix bug of HNSW

### PR DESCRIPTION
**Pull request by hhy3**

### CODE REVIEW

**Comment by hhy3** [comment]
> Could you explain what this is?

When popping the first element of the heap, it could be invalid. So in this case `nvalid` should not decrease by 1. So it should be checked first. Otherwise, the performance would be impaired.

**Comment by mdouze** [comment]
I believe this can happen only if a -1 id gets pushed on the heap, which does never happen, correct?

**Comment by hhy3** [comment]
> I believe this can happen only if a -1 id gets pushed on the heap, which does never happen, correct?

It'll be set to -1 when popping the min element. https://github.com/facebookresearch/faiss/blob/main/faiss/impl/HNSW.cpp#L877
And after I made this modification the recall improved a lot.

**Comment by alexanderguzhva** [comment]
Confirmed.

**Comment by mdouze** [comment]
Thanks a lot for this fix! it increases the accuracy of  HNSW by a lot!

**Pull request closed without merging**
