### PR TITLE
Add IndexScalarQuantizer for c_api

### PR DESCRIPTION
**Pull request by ava57r**

### CODE REVIEW

**Comment by mdouze** [comment]
@Enet4  could you take a look?

**Review by Enet4 — APPROVED** [review]
Looks good to me. :+1:

**Comment by ava57r** [comment]
I would like to add impl `IndexIVFScalarQuantizer` https://github.com/facebookresearch/faiss/blob/master/faiss/IndexScalarQuantizer.h#L82
Can I add this impl here?

**Comment by ava57r** [comment]
more indexes with an `immutable` reference guarantee
https://github.com/Enet4/faiss-rs/issues/11

**Pull request closed without merging**
