### PR TITLE
Add standalone Link-Time Optimization option to CMake

### PR DESCRIPTION
**Pull request by alexanderguzhva**
Adds `-DFAISS_USE_LTO=ON` option to CMake to enable LTO. LTO increases the linking time, but potentially provides a small boost to the whole library.

### CODE REVIEW

**Comment by junjieqi** [comment]
Hi @alexanderguzhva do you want to resolve the conflicts before I merge into Meta side?

**Comment by junjieqi** [comment]
@alexanderguzhva would you mind providing more context for this pr? I'm wondering how we could test the improvement

**Comment by alexanderguzhva** [comment]
@junjieqi Standard benchmarks?

**Comment by junjieqi** [comment]
> @junjieqi Standard benchmarks?

Have you tested on your side? Or we just want to add this option for everyone to test.

**Comment by junjieqi** [comment]
@alexanderguzhva would you like to address the conflict so I could import it?

**Comment by alexanderguzhva** [comment]
@junjieqi my bad :[, sorry

**Pull request closed without merging**
