### PR TITLE
Add the ability to clone and read binary indexes to the C API.

### PR DESCRIPTION
**Pull request by aalekhpatel07**
I noticed we have a pretty decent C API for binary indexes and please correct me if I'm wrong but we seem to be missing a couple of functions, like the ability to clone and read binary indexes. This PR provides those functions.

### CODE REVIEW

**Review by Enet4 — APPROVED** [review]

**Comment by mdouze** [comment]
Thanks!

**Comment by aalekhpatel07** [comment]
Please feel free to let me know if there's anything I can do on my end to fix the CI lint check.

**Comment by algoriddle** [comment]
> Please feel free to let me know if there's anything I can do on my end to fix the CI lint check.

Can you add a line break at the end of the two files, please?

**Review by aalekhpatel07 — COMMENTED** [review]
Add line breaks to clone_index_c.cpp and index_factory_c.cpp

**Pull request closed without merging**
