### PR TITLE
Allow setting nprobe for IndexIDMap->IndexIVF

### PR DESCRIPTION
**Pull request by bvarghese1**

### CODE REVIEW

**Comment by bvarghese1** [comment]
@mdouze Created this PR as per our discussion in https://github.com/facebookresearch/faiss/issues/671
Some of the tests are failing in the CI however, they seem unrelated to this change.

**Comment by mdouze** [comment]
Hmm the errors seem unrelated to the PR. @beauby, any idea of what happens here?

**Comment by beauby** [comment]
Build should be fixed by #687.

**Comment by bvarghese1** [comment]
@mdouze, @beauby Thanks! I have updated the PR.

**Pull request merged**
