### PR TITLE
Remove CMake support.

### PR DESCRIPTION
**Pull request by beauby**

### CODE REVIEW

**Comment by mdouze** [comment]
OK by me. 
Maybe notify the people who wrote the CMakeFiles.

**Comment by beauby** [comment]
cc @hlzz, @Adeykin, @mohnishkodnani – we're removing official CMake support, as we aim to provide only one build system, but if some of you wish to maintain CMakefiles on a different repo, we will link to it from the `INSTALL.md`.

**Comment by hlzz** [comment]
@beauby Sorry to hear that. If possible, you can link to this [faiss fork](https://github.com/hlzz/faiss) that I maintained, which syncs with the latest version with CMake build.

**Comment by woctezuma** [comment]
You might want to remove this line:
> Alternatively, steps 1 and 3 can be built via the cmake scripts (see below).

in https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#compile-from-source

**Pull request merged**
