### PR TITLE
Support for parallelization in IVFFastScan over both queries and probes

### PR DESCRIPTION
**Pull request by alemagnani**
For search request with few queries or single query, this PR adds the ability to run threads over both queries and different cluster of the IVF. For application where latency is important this can **dramatically reduce latency for single query requests**.

A new implementation (#14) is added. The new implementation could be merged to the implementation 12 but for simplicity in this PR, I created a separate function.

Tests are added to cover the new implementation and new tests are added to specifically cover the case when a single query  is used.

In my benchmarks a very good reduction of latency is observed for single query requests.

### CODE REVIEW

**Comment by alemagnani** [comment]
i am not sure why the build on OSX doesn't work. It doesn't seem related to my changes

**Comment by mdouze** [comment]
There is something wrong with the OSX continuous integration, let's ignore for now. 
The tests look fine. 
Could you post some results showing that this outperforms the existing FastScan implementation? Ideally add a self-contained example script in the benchs/ subdirectory.

**Comment by alemagnani** [comment]
I added a specific bench mark using single query request on 50M Bigann.
I am comparing the timing of the batched request vs single query request with original implementation and new implementation using 8 threads. As you can see for larger number of probes the improvements is substantial (more than a factor of 4)

these are the results:

======IVF4096,PQ64x4fs(num_threads=8)
        nprobe   1, 1Recall@64: 0.426900, speed: 0.066297 ms/query
        nprobe   4, 1Recall@64: 0.740900, speed: 0.058711 ms/query
        nprobe   8, 1Recall@64: 0.859400, speed: 0.075914 ms/query
        nprobe  16, 1Recall@64: 0.932700, speed: 0.120361 ms/query
        nprobe  32, 1Recall@64: 0.969500, speed: 0.178624 ms/query
        nprobe  64, 1Recall@64: 0.983300, speed: 0.294141 ms/query
        nprobe 128, 1Recall@64: 0.986400, speed: 0.482581 ms/query
        nprobe 256, 1Recall@64: 0.987200, speed: 0.901893 ms/query
======IVF4096,PQ64x4fs(implem=0)(single_query=True)(num_threads=8)
        nprobe   1, 1Recall@64: 0.426900, speed: 0.249286 ms/query
        nprobe   4, 1Recall@64: 0.740900, speed: 0.576530 ms/query
        nprobe   8, 1Recall@64: 0.859400, speed: 0.937214 ms/query
        nprobe  16, 1Recall@64: 0.932700, speed: 1.739365 ms/query
        nprobe  32, 1Recall@64: 0.969500, speed: 3.157678 ms/query
        nprobe  64, 1Recall@64: 0.983300, speed: 6.033107 ms/query
        nprobe 128, 1Recall@64: 0.986400, speed: 9.168306 ms/query
        nprobe 256, 1Recall@64: 0.987200, speed: 17.328420 ms/query
======IVF4096,PQ64x4fs(implem=14)(single_query=True)(num_threads=8)
        nprobe   1, 1Recall@64: 0.426900, speed: 0.345765 ms/query
        nprobe   4, 1Recall@64: 0.740800, speed: 0.346243 ms/query
        nprobe   8, 1Recall@64: 0.859300, speed: 0.377188 ms/query
        nprobe  16, 1Recall@64: 0.932600, speed: 0.487485 ms/query
        nprobe  32, 1Recall@64: 0.969600, speed: 0.644108 ms/query
        nprobe  64, 1Recall@64: 0.983300, speed: 0.969482 ms/query
        nprobe 128, 1Recall@64: 0.986300, speed: 1.766294 ms/query
        nprobe 256, 1Recall@64: 0.987400, speed: 3.085881 ms/query

**Comment by alemagnani** [comment]
any comment on the benchmarks? anything that needs to be covered? thanks

**Comment by mdouze** [comment]
Sorry for the delay, catching up...

**Pull request closed without merging**
