### PR TITLE
support win arm builds

### PR DESCRIPTION
**Pull request by es0m**
- added ARM64 support for Windows based on OpenBLAS, fixes to __popcnt64 and __lzcnt64
- added testing support for Windows (but needs CMake fixes to support dll copying)
- added build to circle ci (not tested)

if using neon Popcount could be implemented via CNT instruction, see:
https://github.com/barakmich/go-popcount

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
Windows on ARM seems to support popcount, https://godbolt.org/z/En5rEWcn6, no?

**Comment by es0m** [comment]
Sadly, it compiles, but doesn't link: 

4>IndexPQ.obj : error LNK2001: unresolved external symbol __popcnt64
3>IndexPQ.obj : error LNK2001: unresolved external symbol __popcnt64
3>PolysemousTraining.obj : error LNK2001: unresolved external symbol __popcnt64
3>hamming.obj : error LNK2001: unresolved external symbol __popcnt64
3>IndexBinaryHash.obj : error LNK2001: unresolved external symbol __popcnt64
3>IndexBinaryIVF.obj : error LNK2001: unresolved external symbol __popcnt64
3>IndexIVFPQ.obj : error LNK2001: unresolved external symbol __popcnt64
3>IndexIVFSpectralHash.obj : error LNK2001: unresolved external symbol __popcnt64

**Comment by alexanderguzhva** [comment]
@es0m , maybe, this https://godbolt.org/z/7doTcrK1x ? Also, I'm currently adding 2782 which improves hamming distance computation for ARM. Could you please verify that it compiles (with the popcnt change included)? Thanks

**Comment by mdouze** [comment]
We decided to wait that Windows / ARM becomes more popular to integrate it into Faiss.

**Comment by es0m** [comment]
Well, that's a very weird decision as it seems fairly low-risk. Access to a device doesn't seem to be an issue given that you don't run win-x64 tests neither. 
I'm happy to update the PR to the latest main if that helps!

**Pull request closed without merging**
