### PR TITLE
Include libfaiss_python_callbacks.so in python installation.

### PR DESCRIPTION
**Pull request by ccoulombe**
Include `libfaiss_python_callbacks.so` in `setup.py`.

### CODE REVIEW

**Comment by bhatiaharsh** [comment]
I am running into this issue as well. Could you please merge this one in?

**Comment by sdake** [comment]
@bhatiaharsh I have also run into this issue. I am not a maintainer, however, I will (try) to submit a new PR. This solution is pretty close, however, the `rpath` is encoded incorrectly:
```
wise@wise-a40x1-1:~/v-retro/lib/python3.11/site-packages/faiss$ readelf -d _swigfaiss_avx2.so

Dynamic section at offset 0x500608 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libfaiss_avx2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libfaiss_python_callbacks.so]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [_swigfaiss_avx2.so]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/cuda/lib64:/workspace/faiss-1.7.4/_build/faiss:/workspace/faiss-1.7.4/_build/faiss/python]
```

I am actually not sure what needs to happen with rpath with python. I found this related issue: https://github.com/facebookresearch/faiss/issues/2063#issuecomment-925952432 from the same author.

Unfortunately, their CLA has timed out, and like you, I need this asap. I will publish a PR when I find a proper rpath solution. (For more information about rpath, you can read ld.so man page, or try https://en.wikipedia.org/wiki/Rpath).


Thank you,
-steve

**Comment by ccoulombe** [comment]
@mdouze or @beauby Can this be merge please, v1.8.0 still needs this PR to correctly bundle the missing library. Thanks

**Comment by ccoulombe** [comment]
I've now resolved the conflict.

**Comment by sdake** [comment]
adding a quick note that I have solved in faiss 1.7.4 some of the linker errors in the python package. The two patches are here:

https://github.com/artificialwisdomai/origin/blob/main/platform/packaging/build/faiss/faiss-v1.7.4-runpath-origin.patch
https://github.com/artificialwisdomai/origin/blob/main/platform/packaging/build/faiss/faiss-v1.7.4-setuppy-include-binaries.patch

Once I finish a port to 1.8, i will submit the two patches as PRs. Please note that one of these patches mirrors that in this issiue tracker.

**Comment by junjieqi** [comment]
Hi @ccoulombe, would you like to provide some repro steps which I could test on my side? In addition, is it still a problem?

**Comment by ccoulombe** [comment]
@junjieqi Yes, see https://github.com/facebookresearch/faiss/issues/2063 :) 
And yes, it was still an issue for v1.8

**Comment by junjieqi** [comment]
Hi @ccoulombe would you like to update this change and resolve the conflict so we could run it through CI to get signals? Thanks!

**Comment by ccoulombe** [comment]
@junjieqi I've now fixed, again, the conflicts. Please can this be merged before there's new conflicts ? :)

**Comment by sdake** [comment]
@junjieqi @ccoulombe I can submit the remaining work from https://github.com/artificialwisdomai/origin/blob/main/platform/Dockerfiles/faiss/faiss-v1.7.4-runpath-origin.patch. This eliminates the need to hack the runpath so the shared object can be used.

I don't know if you are already working on this @ccoulombe - if so I don't want to step on your contributions. Would you let me know?

TY
-steve

**Comment by ccoulombe** [comment]
@sdake According to my last build for v1.8.0, fixing the rpath was not needed:
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/1c30b4c722d26414f83df7fe982e726a5238a5bc/easybuild/easyconfigs/f/faiss/faiss-1.8.0-gccflexiblascuda-2023a.eb#L43
and no issues arised since.

But this was indeed needed for the prior v1.7.4.

**Comment by sdake** [comment]
Thanks @ccoulombe . I didn't wish to blindly submit a PR as I didn't record a test case, hence didn't know how to verify the problem. I was certain at the time the RPATH override was necessary, although less so now :)

**Pull request closed without merging**
