### PR TITLE
Fix #3379: Add tutorial for HNSW index

### LINKED ISSUE #3379: Add a tutorial for IndexHNSW
# Summary

There are tutorials present for Flat, and IVF but not for HNSW. I believe having a tutorial on HNSW would be helpful.

### PR DESCRIPTION
**Pull request by JayjeetAtGithub**
Fixes #3379

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
Rebased the branch on main

**Comment by JayjeetAtGithub** [comment]
Thanks a lot. I am not a Meta employee though.

**Comment by mlomeli1** [comment]
this is the normal process we follow with submitted PRs @JayjeetAtGithub so don't worry it will get merged once we go through internal review.

**Comment by JayjeetAtGithub** [comment]
Thanks @mlomeli1 for the info

**Pull request closed without merging**
