### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by pletessier**
Hi @mdouze ! Here are some changes discussed in #77 with @jubenjum.

### CODE REVIEW

**Comment by mdouze** [comment]
Thanks for the update @pletessier!

I am a bit reluctant to make separate makefile examples for different minor versions of operating systems, because it means there is a lot of code duplication between them, which is hard to maintain. In that respect the sed command that you had before was better.

**Comment by pletessier** [comment]
I totally understand your concerns about code duplication, but I'm also concerned about the sed command (Murphy's law...), so here is my new proposal : To use an env var $BLASLDFLAGS in the Dockerfile which will overwrite (if defined) the corresponding var in the makefile.inc.Linux file.

What do you think ?

**Comment by mdouze** [comment]
Thanks, that looks better to me. Could you try with `?=` instead of the ifeq? It is more compact. Also, I don't think it is useful to do the test for commented out code.

**Comment by pletessier** [comment]
Wasn't aware of the `?=` operator, that's nice !

**Comment by mdouze** [comment]
Looks good. Thanks!

**Pull request merged**
