### PR TITLE
add a subsection for installation from conda-forge

### PR DESCRIPTION
**Pull request by h-vetinari**
After existing for close to a year and considering the quality (IMO) of the collaboration since then,
I believe it would be reasonable to also mention the conda-forge packages in `INSTALL.md`.

WDYT @mdouze @beauby?

### CODE REVIEW

**Comment by beauby** [comment]
@h-vetinari Yup, makes sense, feel free to open a PR.

**Comment by mdouze** [comment]
Absolutely, thanks for the hard work @h-vetinari!

**Comment by mdouze** [comment]
BTW how can we make that a bit more official? 
Add an entry in the CHANGELOG?
Add an entry in https://github.com/facebookresearch/faiss/wiki/Related-projects ?
Post to the Faiss users group on Facebook to say that we endorse conda-forge?

**Comment by h-vetinari** [comment]
> 
> 
> Absolutely, thanks for the hard work @h-vetinari!

Happy to hear it! :)

> BTW how can we make that a bit more official?
> Add an entry in the CHANGELOG?
> Add an entry in https://github.com/facebookresearch/faiss/wiki/Related-projects ?
> Post to the Faiss users group on Facebook to say that we endorse conda-forge?

All of those sound fine to me - would be better if this comes from the maintainers though...?

**Comment by h-vetinari** [comment]
> 
> 
> BTW how can we make that a bit more official?
> Add an entry in the CHANGELOG?
> Add an entry in https://github.com/facebookresearch/faiss/wiki/Related-projects ?
> Post to the Faiss users group on Facebook to say that we endorse conda-forge?

Now that the win+cuda builds are done, I think it would be a good time to announce that? What do you think?

**Pull request closed without merging**
