### PR TITLE
MOD: add some cpp feature, like distance/norm/inner prod computations

### PR DESCRIPTION
**Pull request by intech07**
I want to invoke norm  computations by using CGO, but I find some functions which have been implemented in cpp are not exported in c api, so I commit the PR to solve the problem.

### CODE REVIEW

**Review by Enet4 — APPROVED** [review]
To me, this seems like an accurate translation to the C API.

**Comment by intech07** [comment]
> To me, this seems like an accurate translation of those functions to the C API.

Thanks, I just need these functions, because I would invoke them to normalize vector in CGO.

**Comment by mdouze** [comment]
LGTM.

**Comment by intech07** [comment]
> Test(s) failing
> Test(s) failing internally on Facebook.
> 
> DETAILS
> If you are a Facebook employee, you can view these tests on Phabricator.

@mdouze Sorry, CI indicates that something failed, but I can't see more detail, please help checking it, then I can fix it ASAP.

**Pull request closed without merging**
