### PR TITLE
Increase discovery timeout for ROCm CI failures

### PR DESCRIPTION
**Pull request by asadoughi**
Differential Revision: D65434932

### CODE REVIEW

**Comment by asadoughi** [comment]
@ItsPitt @iotamudelta Is the AMD CI fleet healthy? It appears we're getting timeouts and test processes getting killed unexpectedly.

**Comment by ItsPitt** [comment]
Checking on them now!

**Comment by ItsPitt** [comment]
We've identified an issue with the runner and are working to resolve.

**Comment by asadoughi** [comment]
Seems to be working fine without the timeout now that the CI fleet is healthy again

**Pull request closed without merging**
