### PR TITLE
CI : job with allowed failure to build C api

### PR DESCRIPTION
**Pull request by glutamatt**
following of https://github.com/facebookresearch/faiss/issues/1139#issuecomment-598350870

I duplicated the first job, adding a env var to init C api compilation
I set this duplicated job as `allow_failures`

image

***

## existing job
image

***

## new job with `allow_failures`
image

### CODE REVIEW

**Comment by glutamatt** [comment]
I had to change and move the condition test in the bash script in order to make it work on darwin environements ( if you compare the actual files diff and the screenshots )

**Comment by mdouze** [comment]
@beauby any opinion on this PR?

**Comment by beauby** [comment]
This would be great. As we moved to CircleCI, the PR would need to be reworked, but it shouldn't take much effort, and the C API build could be a dependent job of the C++ tests.

**Comment by glutamatt** [comment]
It seems that CircleCI doesn't support the "allow_failures" feature : after some search in the circleci forum, there is plenty feature requests and some ugly workarounds.

Do I
 - make the success of C api build mandatory (no failure allowed) ?
 - I close this PR ?
 - I try some ugly workaround ?

**Comment by glutamatt** [comment]
to sum up and check whether i got the context : 
 
**before, with travis**, macOS build success was allowed to fail : i added C api build test optional as well
 travis need the "optional" flag in order the keep the whole build successful even if optional jobs fail

**now with CircleCi**, each job seems independent (add its own github check), and a PR can be merged without all checks pass

correct me if i'm wrong

**Comment by beauby** [comment]
@glutamatt This is correct.

**Comment by glutamatt** [comment]
On master branch ([this commit](https://github.com/facebookresearch/faiss/commit/894116067888089c269f6668f539a4d98f72838e)), the build of `c_api` seems broken 💥 

I achieved to build the faiss library based of commands defined for [circleci](https://github.com/facebookresearch/faiss/blob/894116067888089c269f6668f539a4d98f72838e/.circleci/config.yml#L12-L41)
but then, following [documentation for c_api build](https://github.com/facebookresearch/faiss/blob/894116067888089c269f6668f539a4d98f72838e/c_api/INSTALL.md) does not work anymore

```
root@3005e5307bd1:~/faiss-master/c_api# make
Makefile:10: ../makefile.inc: No such file or directory
make: *** No rule to make target '../makefile.inc'.  Stop.
```

here we have an other example of the need of c_api build check
... maybe something related to the new usage of `cmake`

**Comment by Enet4** [comment]
Yes, this is very likely due to the recent changes in the building system to use CMake instead of GNU autotools.

While I would be interested in migrating the C API to also use this building system, it is something that I am not that familiar with, and for which I cannot define a deadline. Assistance in this process would be greatly appreciated.

**Comment by glutamatt** [comment]
@beauby , please,  your help is needed to get the C api build back on track
:pray:  thanks

**Comment by glutamatt** [comment]
https://github.com/facebookresearch/faiss/pull/1678 seems to supersedes :+1:

**Pull request closed without merging**
