### PR TITLE
AIX compilation fix for io classes

### PR DESCRIPTION
**Pull request by ranjitsastra**
in AIX OS ,as fileno is defined as C macro,   we get the compilation error during preprocessing step.

In file included from /ranjit/Faiss/faiss/faiss/invlists/InvertedListsIOHook.h:10:
/ranjit/Faiss/faiss/faiss/impl/io.h:35:17: error: expected member name or ';' after declaration specifiers
   35 |     virtual int fileno();
      |     ~~~~~~~~~~~ ^
/usr/include/stdio.h:517:30: note: expanded from macro 'fileno'
  517 | #define fileno(__p)     ((__p)->_file)

### CODE REVIEW

**Comment by ranjitsastra** [comment]
issue for this PR is [https://github.com/facebookresearch/faiss/issues/3274](url)

**Comment by ranjitsastra** [comment]
issue for this PR is [https://github.com/facebookresearch/faiss/issues/3274](url)

**Comment by mdouze** [comment]
I am not overly enthusiastic about the new name, but if we can unblock people, let's do it.

**Comment by ranjitsastra** [comment]
@mdouze  @junjieqi 
Thanks you for reviewing and merging this PR.

**Pull request closed without merging**
