### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by alues**
*Update install instructions for docker build from Github repo*
module `jupyter` added for easy testing

### CODE REVIEW

**Comment by alues** [comment]
@beauby @mdouze

**Comment by alues** [comment]
@beauby shall we merge it?

**Comment by alues** [comment]
@mdouze shall we merge it?

**Comment by mdouze** [comment]
Is this outdated by #526 ?

**Comment by alues** [comment]
@mdouze i don't think so, `jupyter` added for easy testing, why this PR not merge?

**Comment by beauby** [comment]
Thanks for your work @alues, however we will go with @pletessier's PR instead as he is the current maintainer of that file.

**Pull request closed without merging**
