### PR TITLE
IO support for IndexNNDescent

### PR DESCRIPTION
**Pull request by KinglittleQ**
This PR added I/O methods for IndexNNDescent.

Closes https://github.com/facebookresearch/faiss/issues/2125

### CODE REVIEW

**Comment by mdouze** [comment]
LGTM. See one small comment.

**Comment by KinglittleQ** [comment]
Hi, what comment are you referring to?

**Comment by mdouze** [comment]
> Hi, what comment are you referring to?
 the one about the desrialize_index

**Comment by CaucherWang** [comment]
Maybe it's also helpful to save nn-descent during building nsg.

**Comment by mdouze** [comment]
> Did you leave any comments during the review? I can't see them here. Maybe there is something wrong with Github.

Nothing significant. The PR was committed.

**Pull request closed without merging**
