### PR TITLE
add batch reconstruction function

### PR DESCRIPTION
**Pull request by mdouze**
Summary:
As requested in https://github.com/facebookresearch/faiss/issues/1163
add `reconstruct_batch` that calls `reconstruct` in a C++ for loop.

Differential Revision: D37717342

### CODE REVIEW

**Comment by urialon** [comment]
Wow, thanks a lot @mdouze !!
Is there a version release expected soon, or should I build from sources (after the merge) to use this?

**Comment by mdouze** [comment]
I'll fix the CI errors first...

**Comment by guillaumeguy** [comment]
Too bad this closed! It would be quite useful.

**Comment by mdouze** [comment]
> Too bad this closed! It would be quite useful.

It is supported see 
https://github.com/facebookresearch/faiss/blob/e3731f7886dd0f240ac3addfdada8e12ffadb658/tests/test_build_blocks.py#L603

**Pull request closed without merging**
