### PR TITLE
Workaround for missing intrinsic on gcc < 9

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
lgtm

**Comment by junjieqi** [comment]
@borrrden  could you try to rebase this diff with master? I found I can't rebase it from our side.

**Comment by borrrden** [comment]
I can't rebase the branch because it's a branch we are using for production based on a release tag from your repo so I will need to recreate this PR.

**Comment by borrrden** [comment]
@junjieqi See #3481

**Pull request closed without merging**
