### PR TITLE
Disable the NEON optimisations on gcc <= 8

### PR DESCRIPTION
**Pull request by JAicewizard**
GCC7 doesnt support all the necessary NEON intrinsics, which is really a shame. However this means that for aarch64 GCC cannot compile faiss with neon intrinsics, so we should avoid using them.

This is similar to #3860, build issues on GCC7, which I need. This one is a bit uglier, since GCC7 does support NEON just not all of the intrinsics.

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
@JAicewizard this should not affect `clang`, correct? because `clang` tends to pretend in certain situations

**Comment by JAicewizard** [comment]
I just checked on CC explorer [here](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,source:'%23include+%3Cstdint.h%3E%0A%23ifdef+__ARM_NEON%0Avoid+foo(uint64_t+blocks%5B%5D)+%7B%0A++blocks+%3D+__builtin_assume_aligned(blocks,+64)%3B%0A++for+(intptr_t+i+%3D+0+%3B+i%3C10240+%3B+i%2B%3D2)+%7B%0A++++uint64_t+x+%3D+blocks%5Bi%5D%3B%0A++++uint64_t+y+%3D+blocks%5Bi%2B1%5D%3B%0A++++blocks%5Bi%5D+%3D+x%5Ey%3B%0A++++blocks%5Bi%2B1%5D+%3D+x%26y%3B%0A++%7D%0A%7D%0A%23endif%0A/*%0A+*/%0A%0A%0A%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:38.62987630827783,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:armg630,filters:(b:'0',directives:'0',intel:'0'),options:'-xc+-std%3Dgnu11+-O3+-Wall+-march%3Darmv7-a+-mfpu%3Dneon+-mneon-for-64bits+-marm+-dM+-E',source:1),l:'5',n:'0',o:'ARM+gcc+6.3.0+(Editor+%231,+Compiler+%232)',t:'0')),header:(),k:100,l:'4',m:45.83385280305864,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armhfg54,filters:(___0:(),b:'0',directives:'0',intel:'0',jquery:'3.2.1',length:1,prevObject:(___0:(sizzle1504823907290:(undefined:(legend:!(15,0,'1')))),length:1,prevObject:(___0:(jQuery321090780179552843851:(display:''),sizzle1504823907290:(undefined:(legend:!(15,0,'1')))),length:1))),options:'-xc+-O3+-Wall+-march%3Darmv7-a+-mfpu%3Dneon+-mneon-for-64bits+-marm',source:1),l:'5',n:'0',o:'ARM+gcc+5.4+(Editor+%231,+Compiler+%233)',t:'0')),header:(),k:61.37012369172218,l:'4',m:54.16614719694135,n:'0',o:'',s:0,t:'0')),k:61.37012369172218,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) and even with the oldest aarch64 clang there were no issues. So there might be an old clang compiler that doesn't work, but I am not in a position to test all of them. I suspect they were just always supported.

**Comment by JAicewizard** [comment]
This should be fixed now

**Comment by junjieqi** [comment]
github action failed. @JAicewizard could you help fix them before I import again? Thanks!

**Comment by JAicewizard** [comment]
I pushed some changes, but I don't think they will fix the error on your end. If anyone could post them I can look into it

**Comment by junjieqi** [comment]
@JAicewizard here is some errors. Thanks for your patience.

```
fbcode/faiss/impl/ScalarQuantizer.cpp:62:9: error: expected unqualified-id
   62 |         vld1q_f32_x2(const float32_t* __a) {
      |         ^
fbcode/third-party-buck/platform010-aarch64/build/llvm-fb/17/lib/clang/stable/include/arm_neon.h:9823:28: note: expanded from macro 'vld1q_f32_x2'
 9823 | #define vld1q_f32_x2(__p0) __extension__ ({ \
      |                            ^
```

**Pull request closed without merging**
