### PR TITLE
Introduce result collector for HNSW

### PR DESCRIPTION
**Pull request by heemin32**
Introduce result collector for HNSW

The result collector is to be used by caller to implement their own logic to collect result. One of example is deduplicating result based on group id. https://github.com/facebookresearch/faiss/issues/3087

### CODE REVIEW

**Comment by mdouze** [comment]
Thanks for the PR. 

It would indeed be useful to have a `ResultCollector` object to support knn / range search transparently, and possibly deduplication. 
The result collector would be a class of the form: 

```c++
struct ResultCollector {
    float threshold; // result will be added if distance < threshold 
    virtual bool add_result(idx_t id, float dis) = 0; // returns whether the result was added and the threshold was updated.
};
```

It can be provided to the Index's search function for a given query (like `HNSW::search_from_candidates`). 

The advantage of having an abstract class for `ResultCollector` rather than a template is that it can be provided from an external caller. Besides, since the comparison with the `threshold` (with `C::cmp`) is performed prior to calling the virtual function, there is no possibly slow virtual function call for all computed distances, only for the ones that pass the comparison. 

There are already ResultCollector objects in [IndexIVFPQ](https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp#L754) and [IndexIVFPQFastScan](https://github.com/facebookresearch/faiss/blob/main/faiss/impl/simd_result_handlers.h). 

The ResultCollector in this PR is of too limited scope to be useful, since it does not enable the range search support and calling externally.

**Comment by heemin32** [comment]
Thanks for the comment. I get the point that it does not support for range search. However, what do you mean by saying "calling externally"?

**Comment by mdouze** [comment]
I don't think the resultcollector could replace search and range_search functions because these take batches of queries while the resultcollector is for lower level calls and not thread-safe. 
It would remain an internal function of the indexes.

**Comment by heemin32** [comment]
1. If ResultCollector is not passed through top level method like search and range_search, it cannot be overridden by another collector. 
2. Because it is not thread-safe, we need factory or something else to create ResultCollector per thread anyway

Another option is passing ResultCollector factory through HNSWSearchParameter as this PR and make its interface more generic so that both knn search and range search can be supported transparently.

**Comment by mdouze** [comment]
Please hold on implementing anything. We are currently discussing how to refactor the code with more `ResultHandler`s.

**Comment by heemin32** [comment]
Good to know that discussion is going on regarding ResultHandler. Hope that new plan also include the deduplication use case.

**Pull request closed without merging**
